- alias: Register door code Will Farrington
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: script.register_door_access_code
    data:
      description: "Will Farrington"
      slot: 2
      code: !secret front_door_access_will_farrington

- alias: Register door code Philip Mallory
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: script.register_door_access_code
    data:
      description: "Philip Mallory"
      slot: 3
      code: !secret front_door_access_philip_mallory

# - alias: Notify Slack when the front door is unlocked
#   trigger:
#     platform: state
#     entity_id: lock.schlage_deadbolt_3
#     state: 'unlocked'
#   action:
#   - service: notify.slack
#     data:
#       message: ":unlock: Someone just unlocked the front door!"

# - alias: Notify Slack when the front door is locked
#   trigger:
#     platform: state
#     entity_id: lock.schlage_deadbolt_3
#     state: 'locked'
#   action:
#   - service: notify.slack
#     data:
#       message: ":lock: The front door is locked now!"

# - alias: Lock battery level
#   trigger:
#     platform: numeric_state
#     entity_id: lock.schlage_deadbolt_3
#     value_template: '{{ float(state.attributes.battery_level[:-1]) }}'
#     below: 10.0
#   action:
#   - service: notify.slack
#     data:
#       message: ":battery: Front door lock batteries are below 10%, replace ASAP!"