- alias: Notify Slack when the front door is unlocked
  trigger:
    platform: state
    entity_id: lock.schlage_deadbolt_3
    state: 'unlocked'
  action:
  - service: notify.slack
    data:
      message: ":unlock: Someone just unlocked the front door"

- alias: Notify Slack when the front door is locked
  trigger:
    platform: state
    entity_id: lock.schlage_deadbolt_3
    state: 'locked'
  action:
  - service: notify.slack
    data:
      message: ":unlock: Someone just unlocked the front door"