---
mode: development
cognito_client_id: !secret cloud_cognito_client_id
user_pool_id: !secret cloud_user_pool_id
region: !secret cloud_region
relayer: !secret cloud_relayer
alexa:
  filter:
    exclude_domains:
      - automation
      - group
      - alert
      - lock
      - sensor
      - light
    include_entities:
      - light.entryway
      - light.dining_room
      - light.kitchen
      - light.living_room
      - light.upper_stairs
      - light.upstairs_landing
      - light.master_bedroom
      - light.guest_bedroom
      - group.upstairs_lights
      - group.downstairs_lights
    # include_domains:
    #   - light
