---
alexa:
  filter:
    exclude_domains:
      - automation
      - group
      - alert
      - lock
      - sensor
      - light
    include_entities:
      - light.entryway
      - light.dining_room
      - light.kitchen
      - light.living_room
      - light.upper_stairs
      - light.upstairs_landing
      - light.master_bedroom
      - light.guest_bedroom
      - group.upstairs_lights
      - group.downstairs_lights
      - light.all_hue_lights
    # include_domains:
    #   - light
