---
- platform: webostv
  host: !secret webostv_host
  mac: !secret webostv_mac
  name: Living Room TV
  customize:
    sources:
      - livetv
      - netflix
      - youtube

- platform: sonos
  name: Sonos
  entity_namespace: sonos

