platform: template
switches:
  stream_mode:
    friendly_name: Stream Mode
    value_template: "{{ is_state('light.dining_room', 'brightness', 254) }}"
    turn_on:
      service: scene.turn_on
      entity_id: scene.gaming_mode
    turn_off:
      service: scene.turn_off
      entity_id: scene.gaming_mode